Share Component
yalla-coop/scouts pull request #100
Opened 2021-01-25 16:43 UTC by harleyjm

#80 

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-26 12:20 UTC, RamyAlshurafa requested changes
Hey @harleyjm 
I'm unable to run the PR locally, it throws `Unable to resolve path to module 'react-share' ` so you need to `npm i react-share`
and also add `package.json` and `package-lock.json` to the PR

2021-01-26 17:34 UTC, RamyAlshurafa reviewed
Really nice work @harleyjm 
but left some comments for you
\+ the Twitter icon is not there in the design, and when you add all of them into component they disappear in the mobile because there is no enough space

![image](https://user-images.githubusercontent.com/34629478/105881722-852b9780-600d-11eb-90e2-4e3fb035702d.png)

2021-01-26 17:34 UTC, RamyAlshurafa commented on client/package.json
> +    "storybook": "^6.1.15",
```suggestion
```

why did you install this? i think its not needed and the required modules already listed in the devDependencies in the package.json

2021-01-26 17:34 UTC, RamyAlshurafa commented on client/src/components/Share/index.js
> +const Share = ({ text, facebook, twitter, email, whatsapp }) => {
you can give the text a defualt value
```suggestion
const Share = ({ text = 'Share this page', facebook, twitter, email, whatsapp }) => {
```

in this way, you don't have to give it that same value each time you use this component, and you can just overwrite it if you want a different text

2021-01-26 17:34 UTC, RamyAlshurafa commented on client/src/components/Share/style.js
> +export const Text = styled('span')`
you can use our common Typography component instead of this, this should be Body16 component

2021-01-26 17:38 UTC, harleyjm commented on client/package.json
> +    "storybook": "^6.1.15",
It's not needed, I think it was added when I was trying to correct a storybook error yesterday

2021-01-26 17:41 UTC, harleyjm commented on client/src/components/Share/style.js
> +export const Text = styled('span')`
Sorry didn't realise there was a common typography component. I am still playing catchup having only looked at this yesterday.

2021-01-27 11:13 UTC, RamyAlshurafa approved these changes
Awsome @harleyjm , all perfect :)

2021-01-27 11:13 UTC, merged