72 i can edit an individual skill hq(front-end)
yalla-coop/scouts pull request #108
Opened 2021-01-27 13:32 UTC by fadeomar

#### Issues this PR relates to
#72 
---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-27 18:28 UTC, RamyAlshurafa requested changes

2021-01-27 18:28 UTC, RamyAlshurafa commented on client/src/components/SkillModal/style.js
> +    overflow-y: hidden;
make it `auto` so its scrollable on mobiles

2021-01-27 18:28 UTC, RamyAlshurafa commented on client/src/components/SkillModal/style.js
> +  }
```suggestion
```

2021-01-28 09:14 UTC, fadeomar commented on client/src/components/Inputs/Textarea/style.js
> +  ${CS.placeholderStyle}
done for all  `${setMargin}` without the semicolon

2021-01-28 09:16 UTC, fadeomar commented on client/src/components/SkillModal/style.js
> +    overflow-y: hidden;
done

2021-01-28 09:18 UTC, fadeomar commented on client/src/components/SkillModal/style.js
> +  }
done

2021-01-28 09:19 UTC, fadeomar commented on client/src/components/SkillModal/index.js
> +            style={{ marginTop: 54, border: 'none' }}
done

2021-01-28 09:20 UTC, fadeomar commented on client/src/components/Inputs/Textarea/index.js
> +const BasicInput = ({
done

2021-01-28 09:21 UTC, fadeomar commented on client/src/components/SkillModal/index.js
> +            placeholder="Lots of text to go here that describes the skill and provides context on what you need to do to complete the task"
done

2021-01-28 10:56 UTC, RamyAlshurafa approved these changes

2021-01-28 10:56 UTC, merged