61 recommended skills page fron end
yalla-coop/scouts pull request #114
Opened 2021-01-28 15:27 UTC by fadeomar

#### Issues this PR relates to
#61 

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-28 18:49 UTC, thejoefriel requested changes
- [x] Can't say how it's happened but the button on the digital skills blue card on landing page has disappeared on your PR and is replaced with a url : 
![image](https://user-images.githubusercontent.com/19708921/106183456-23e3ff80-6198-11eb-8bde-eaa67eeb9992.png)

- [ ] When you reduce the browser width the images shrink quite significantly. This shouldn't shrink as much: https://www.loom.com/share/0ef8e979025d42a8946ec6ad7f345cce

2021-01-28 18:49 UTC, thejoefriel commented on client/src/pages/RecommendedSkills/index.js
> +              title="all Skills"
Should be 'All Skills'

2021-01-28 18:49 UTC, thejoefriel commented on client/src/components/Card/RecommendSkill/index.js
> +    <S.Container>
These should be links that take you to the skill, so I'd change these to links, and pass down the skill id as a prop

2021-01-28 18:49 UTC, thejoefriel commented on client/src/components/Icon/icons/Trophy.js
> +      stroke-width="3"
make all of these across the icons camelCase to avoid all the console warnings

2021-01-28 18:49 UTC, thejoefriel commented on client/src/pages/RecommendedSkills/dummyData.js
> +    level: '2',
You have put in level 2 but all the cards are showing as 2-4?

2021-01-29 18:48 UTC, fadeomar commented on client/src/pages/RecommendedSkills/index.js
> +              title="all Skills"
done

2021-01-29 18:53 UTC, fadeomar commented on client/src/components/Card/RecommendSkill/index.js
> +    <S.Container>
done

2021-01-29 18:54 UTC, fadeomar commented on client/src/components/Icon/icons/Trophy.js
> +      stroke-width="3"
done

2021-01-29 18:56 UTC, fadeomar commented on client/src/pages/RecommendedSkills/dummyData.js
> +    level: '2',
done

2021-01-30 17:17 UTC, thejoefriel approved these changes

2021-01-30 17:18 UTC, merged