62 single skill volunteer 2
yalla-coop/scouts pull request #116
Opened 2021-01-28 16:54 UTC by RamyAlshurafa

#### Issues this PR relates to
#62

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-30 17:36 UTC, thejoefriel requested changes
- [x] Reduce spacing between you're doing great card and the cards above. Should be 64px 
![image](https://user-images.githubusercontent.com/19708921/106363398-39843100-6320-11eb-87f7-4166bd736449.png)

2021-01-30 17:36 UTC, thejoefriel commented on client/src/App.js
> +                allowedRoles={[roles.VOLUNTEER]}
- [ ] I can't seem to access the skills unless logged in as a volunteer? They should be publicly available but if you're not logged in then you see this version of the page instead: https://www.figma.com/file/9oFoQawgjFYwHi1dG77RH7/The-Scouts-Association-MVP?node-id=1449%3A5804

2021-01-30 17:36 UTC, thejoefriel commented on client/src/components/Card/ActivityCard/style.js
> +  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.03), 0px 1px 8px rgba(0, 0, 0, 0.05),
use the theme shadow

2021-01-30 17:36 UTC, thejoefriel commented on client/src/components/Icon/icons/ArrowDown.js
> +      stroke-width="2.4"
change all these in icons to camel case to reduce console warnings

2021-01-30 17:36 UTC, thejoefriel commented on client/src/components/Icon/icons/CupWithFlash.js
> +      stroke={strokeColor}
same on this file as above

2021-01-30 17:36 UTC, thejoefriel commented on client/src/pages/VolunteerIndividualSkill/style.js
> +  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.03), 0px 1px 8px rgba(0, 0, 0, 0.05),
use shadow from theme

2021-01-31 08:10 UTC, RamyAlshurafa commented on client/src/components/Card/ActivityCard/style.js
> +  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.03), 0px 1px 8px rgba(0, 0, 0, 0.05),
done

2021-01-31 08:12 UTC, RamyAlshurafa commented on client/src/components/Icon/icons/ArrowDown.js
> +      stroke-width="2.4"
done

2021-01-31 08:13 UTC, RamyAlshurafa commented on client/src/components/Icon/icons/CupWithFlash.js
> +      stroke={strokeColor}
done

2021-01-31 08:13 UTC, RamyAlshurafa commented on client/src/pages/VolunteerIndividualSkill/style.js
> +  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.03), 0px 1px 8px rgba(0, 0, 0, 0.05),
done

2021-01-31 08:30 UTC, RamyAlshurafa commented on client/src/App.js
> +                allowedRoles={[roles.VOLUNTEER]}
done

2021-01-31 11:56 UTC, thejoefriel approved these changes

2021-01-31 11:57 UTC, merged