47 circle diagram score
yalla-coop/scouts pull request #87
Opened 2021-01-19 10:46 UTC by fadeomar

#### Issues this PR relates to
#47 
---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-19 17:15 UTC, RamyAlshurafa requested changes

2021-01-19 17:15 UTC, RamyAlshurafa commented on client/src/theme/index.js
> +  skyBlue: '#e5effa',
```suggestion
```
this is not a new coluor (its blue with opacity = 0.1) so you can make it instead of this
```jsx
          trailColor={theme.colors.skyBlue}
```
 to be used like this

```jsx
        trailColor={`${theme.colors.blue}10`}
```

2021-01-19 17:15 UTC, RamyAlshurafa commented on client/src/components/CircleDigram/CircleDigram.stories.js
> +import CircleDigram from '.';
```suggestion
import CircleDiagram from '.';
```

2021-01-20 08:15 UTC, fadeomar commented on client/src/components/CircleDigram/CircleDigram.stories.js
> +import CircleDigram from '.';
done

2021-01-20 08:19 UTC, fadeomar commented on client/src/components/CircleDigram/style.js
> +  margin-top: 200px;
done

2021-01-20 08:21 UTC, fadeomar commented on client/src/components/CircleDigram/style.js
> +  position: relative;
moved the margin-left to story style, but the remaining style is part of the component

2021-01-20 08:23 UTC, fadeomar commented on client/src/components/CircleDigram/style.js
> +  justify-content: center;
this is part of the component to create a layer above the component to display the content because there is no way to pass custom content inside the circle

2021-01-20 08:26 UTC, fadeomar commented on client/src/components/CircleDigram/style.js
> +  }
done

2021-01-20 08:28 UTC, fadeomar commented on client/src/theme/index.js
> +  skyBlue: '#e5effa',
cool, nice one!

2021-01-20 08:29 UTC, fadeomar commented on client/src/components/CircleDigram/style.js
> +  margin-top: 200px;
done

2021-01-20 08:30 UTC, fadeomar commented on client/src/components/CircleDigram/style.js
> +  position: relative;
done

2021-01-20 09:28 UTC, RamyAlshurafa commented on client/src/components/CircleDigram/style.js
> +  }
i meant to add it to global style

2021-01-20 09:28 UTC, RamyAlshurafa approved these changes

2021-01-20 09:28 UTC, merged