45 question progress bar
yalla-coop/scouts pull request #88
Opened 2021-01-19 14:30 UTC by fadeomar

#### Issues this PR relates to
#45 
---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-19 16:27 UTC, RamyAlshurafa requested changes
Great job @fadeomar 

just minor things

2021-01-19 16:27 UTC, RamyAlshurafa commented on client/src/components/ProgressBar/ProgressBar.stories.js
> +  title: '4- Progress Bar',
make it under common components

2021-01-19 16:27 UTC, RamyAlshurafa commented on client/src/components/ProgressBar/style.js
> +    margin-right: 4px !important;
use spacings from the theme

2021-01-19 16:27 UTC, RamyAlshurafa commented on client/src/components/ProgressBar/style.js
> +    width: calc(100% - 45px) !important;
use spacings from the theme

2021-01-19 16:27 UTC, RamyAlshurafa commented on client/src/components/ProgressBar/index.js
> +import { Body16B } from '../Typography';
I think we should consistent with this syntax
```suggestion
import * as T from '../Typography';
```
and then you use it like this
`<T.Body16B color="blue">{currentLocation}</T.Body16B>`

2021-01-19 16:27 UTC, RamyAlshurafa commented on client/src/components/ProgressBar/index.js
> +    <Container stepes={stepes}>
```suggestion
    <Container steps={steps}>
```

and check if used in other places

2021-01-19 16:27 UTC, RamyAlshurafa commented on client/src/components/ProgressBar/ProgressBar.stories.js
> +      name: 'progress Persentage',
```suggestion
      name: 'progress Percentage',
```

2021-01-20 08:49 UTC, fadeomar commented on client/src/components/ProgressBar/ProgressBar.stories.js
> +  title: '4- Progress Bar',
done

2021-01-20 08:55 UTC, fadeomar commented on client/src/components/ProgressBar/style.js
> +    margin-right: 4px !important;
done

2021-01-20 08:57 UTC, fadeomar commented on client/src/components/ProgressBar/style.js
> +    width: calc(100% - 45px) !important;
here I cant using spacing from them because there is no equivalent value for 45px, also its fixed value the divs in the bar is changing their width according to screen width but the percentage text are fixed everywhere

2021-01-20 08:58 UTC, fadeomar commented on client/src/components/ProgressBar/index.js
> +import { Body16B } from '../Typography';
done

2021-01-20 08:58 UTC, fadeomar commented on client/src/components/ProgressBar/index.js
> +    <Container stepes={stepes}>
done

2021-01-20 08:59 UTC, fadeomar commented on client/src/components/ProgressBar/ProgressBar.stories.js
> +      name: 'progress Persentage',
done

2021-01-20 11:07 UTC, RamyAlshurafa approved these changes

2021-01-20 13:31 UTC, merged