24/25/28 file structure and database
yalla-coop/scouts pull request #89
Opened 2021-01-19 14:49 UTC by RamyAlshurafa

#### Issues this PR relates to
#24 
#25 
#28

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-19 17:27 UTC, thejoefriel requested changes
- activities seemed to get created twice. Is that right?
<img width="1920" alt="Screenshot 2021-01-19 at 17 06 01" src="https://user-images.githubusercontent.com/19708921/105068275-aa059500-5a78-11eb-8a8a-ba1ef11894e8.png">

- I don't think this was on your PR but the migrations.sql file I've noticed has a bunch of migrations from the Tempo project! Do you mind removing please?

2021-01-19 17:27 UTC, thejoefriel commented on server/database/models/activities/schema.sql
> +  "description" TEXT NOT NULL,
In the database after the build, I'm not getting any descriptions stored. I'm wondering if it's because this is text and it should be varchar? Not sure but I can see you've put description in the dummy data so there seems to be an issue here

2021-01-19 17:27 UTC, thejoefriel commented on server/database/dummy-data/skills.js
> +      code: 'TURN_ON_DEVICE',
I noticed in the database that we've got an icon data field but we haven't stored an icon names - is that right?

2021-01-19 17:27 UTC, thejoefriel commented on server/database/dummy-data/users.js
> +      assessmentScore: 2050,
The score should really be up to max 100 so for these dummy ones, can we put them at under 100 to make sure we get an accurate looking score to track the progress. 
Same for improvement score

2021-01-19 17:27 UTC, thejoefriel commented on server/database/models/users-check-ins/schema.sql
> +DROP TABLE IF EXISTS "users_checks_ins" CASCADE;
please call this 'user_check_ins' instead

2021-01-19 17:27 UTC, thejoefriel commented on server/database/models/users-check-ins/schema.sql
> +DROP TABLE IF EXISTS "users_checks_ins" CASCADE;
also should we have some dummy data for this?

2021-01-19 17:27 UTC, thejoefriel commented on server/database/dummy-data/users-completed-activities.js
> +      addedScore: 700,
can we make this a more realistic score (e.g. 3)

2021-01-19 17:27 UTC, thejoefriel commented on server/database/dummy-data/users-skills.js
> +      addedScore: 1250,
same here as with the other scores, let's make more like 5

2021-01-19 17:27 UTC, thejoefriel commented on server/constants/data-types.js
> +  QUEUED: 'QUEUED',
I was thinking about this a bit more, do we actually need queued? We definitely need already has and completed, but wouldn't we know all remaining skills from the relevant skill areas for the user that are not marked as either already has or completed?

2021-01-19 17:27 UTC, thejoefriel commented on server/database/dummy-data/organisations.js
> +  const AvonTyrrellOrg = await createOrganisation(['Avon Tyrrell']);
Let's make at least one of these Scouts since this will most likely be the only organisation using the platform in the medium term

2021-01-19 17:27 UTC, thejoefriel commented on server/constants/index.js
> +export * from './data-types';
I noticed skill codes or skill area codes aren't stored as constants. Should we do this so that there's one place where these can be checked/updated?

2021-01-19 18:26 UTC, RamyAlshurafa commented
> activities seemed to get created twice. Is that right?
 
fixed

> I don't think this was on your PR but the migrations.sql file I've noticed has a bunch of migrations from the Tempo project! Do you mind removing please?

oops, fixed

2021-01-19 18:28 UTC, RamyAlshurafa commented on server/database/models/activities/schema.sql
> +  "description" TEXT NOT NULL,
can you double-check again please

2021-01-19 18:34 UTC, RamyAlshurafa commented on server/database/dummy-data/skills.js
> +      code: 'TURN_ON_DEVICE',
yeah we should have, i added a "default" icon for all of them

2021-01-19 19:35 UTC, RamyAlshurafa commented on server/database/models/users-check-ins/schema.sql
> +DROP TABLE IF EXISTS "users_checks_ins" CASCADE;
done

2021-01-19 19:47 UTC, RamyAlshurafa commented on server/constants/data-types.js
> +  QUEUED: 'QUEUED',
yeah you are right, fixed

2021-01-19 19:52 UTC, RamyAlshurafa commented on server/database/dummy-data/organisations.js
> +  const AvonTyrrellOrg = await createOrganisation(['Avon Tyrrell']);
done

2021-01-19 20:00 UTC, RamyAlshurafa commented on server/constants/index.js
> +export * from './data-types';
good idea, done

2021-01-19 20:20 UTC, RamyAlshurafa commented on server/database/dummy-data/users-skills.js
> +      addedScore: 1250,
this was meant to equal 12.5% because dealing with float numbers require us to format them into 2 decimals, but will change it to Real type

2021-01-19 20:20 UTC, RamyAlshurafa commented on server/database/dummy-data/users-completed-activities.js
> +      addedScore: 700,
this equal 7

2021-01-19 20:20 UTC, RamyAlshurafa commented on server/database/dummy-data/users.js
> +      assessmentScore: 2050,
done

2021-01-20 09:26 UTC, thejoefriel commented on server/database/models/activities/schema.sql
> +  "description" TEXT NOT NULL,
Hmm, it's not showing in PSequel but I ran the command in my terminal and it is there, so I'm assuming it's a PSequel quirk. Happy to mark this as resolved

2021-01-20 09:28 UTC, thejoefriel approved these changes

2021-01-20 09:28 UTC, merged