Create all inputs
yalla-coop/scouts pull request #90
Opened 2021-01-19 16:39 UTC by thejoefriel

#### Issues this PR relates to
#38 

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

Run everything in storybook

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-19 18:19 UTC, RamyAlshurafa reviewed
all good Joe
just console warnings :)

2021-01-19 18:19 UTC, RamyAlshurafa commented on client/src/components/Inputs/Radio/index.js
> +const Field = styled.div`
move the style from the components files, you can have one style file for all the inputs components

2021-01-19 18:19 UTC, RamyAlshurafa commented on client/src/components/Inputs/Cards/index.js
> +      {options.map((option) => (
need key, it could be `option.label`

2021-01-19 18:19 UTC, RamyAlshurafa commented on client/src/components/Inputs/Options/index.js
> +      {options.map((option) => (
need a key, it could be `option.title`

2021-01-19 18:19 UTC, RamyAlshurafa commented on client/src/components/Inputs/Dropdown/index.js
> +      return options.map(({ groupLabel, options: _options }) => (
add key props

2021-01-19 18:19 UTC, RamyAlshurafa commented on client/src/components/Inputs/Dropdown/index.js
> +          {_options.map((opt) => (
same here (key)

2021-01-19 18:19 UTC, RamyAlshurafa commented on client/src/components/Inputs/Dropdown/index.js
> +    return options.map(({ value: _value, label: _label }) => (
same here (key)

2021-01-19 18:19 UTC, RamyAlshurafa commented on client/src/components/Inputs/Matrix/index.js
> +      {rows.map(({ label, value, options }) => (
same here (key)

2021-01-19 18:19 UTC, RamyAlshurafa commented on client/src/components/Inputs/Radio/index.js
> +        {options.map((opt) => (
same here (key)

2021-01-19 19:08 UTC, RamyAlshurafa requested changes

2021-01-19 19:08 UTC, RamyAlshurafa commented on client/src/components/Inputs/Inputs.stories.js
> +
```suggestion
const SliderExample = (args) => {
  const [selected, setSelected] = useState(() => {
    if (args.options.length % 2 === 0) return { ...args.options[0], key: 0 };
    const middleNum = Math.floor(args.options.length / 2);
    return { ...args.options[middleNum], key: middleNum };
  });

  const handleChange = (e) => {
    console.log(e, '------');
    setSelected({ ...args.options[e], key: e });
  };

  return (
    <Row>
      <Col w={[4, 6, 4]}>
        <Slider {...args} selected={selected} handleChange={handleChange} />
      </Col>
    </Row>
  );
};

```

this is a vital thing for performance since `args` is a reference (object), so the useEffect will be called on each change in its parent, and this component will make unnecessary renders

2021-01-20 09:51 UTC, thejoefriel commented on client/src/components/Inputs/Radio/index.js
> +const Field = styled.div`
Cool. I haven't moved all the styles into one style file as I found when we did this with Tempo it quickly became very inaccessible to use. However, I've created one common style file where there's styling that can be applied across components, and I've also broken out the others into separate style files. Hope you agree that works :)

2021-01-20 09:52 UTC, thejoefriel commented on client/src/components/Inputs/Cards/index.js
> +      {options.map((option) => (
done

2021-01-20 09:53 UTC, thejoefriel commented on client/src/components/Inputs/Dropdown/index.js
> +      return options.map(({ groupLabel, options: _options }) => (
these all already have keys?

2021-01-20 09:54 UTC, thejoefriel commented on client/src/components/Inputs/Dropdown/index.js
> +          {_options.map((opt) => (
it has keys? The AntdOptGroup has key on l.45 and the AntdOption has a key on l.49

2021-01-20 09:55 UTC, thejoefriel commented on client/src/components/Inputs/Radio/index.js
> +        {options.map((opt) => (
done

2021-01-20 09:56 UTC, thejoefriel commented on client/src/components/Inputs/Inputs.stories.js
> +
cool makes sense

2021-01-20 11:00 UTC, RamyAlshurafa approved these changes

2021-01-20 11:01 UTC, merged