Create digital test landing page > #53
yalla-coop/scouts pull request #96
Opened 2021-01-22 18:37 UTC by thejoefriel

#### Issues this PR relates to
#53 

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

go to /digital-test

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-25 11:34 UTC, RamyAlshurafa requested changes

2021-01-25 11:34 UTC, RamyAlshurafa commented on client/src/pages/TestLanding/index.js
> +const Landing = () => {
make the name of the component matches the folder name, so its easier to find when using the react chrome extention

2021-01-25 11:34 UTC, RamyAlshurafa commented on client/src/pages/TestLanding/style.js
> +  ${setMargin}
```suggestion
  ${setMargin};
```

2021-01-25 11:34 UTC, RamyAlshurafa commented on client/src/pages/TestLanding/index.js
> +      {/* <BackLink mb="5" /> */}
do you need this?

2021-01-25 11:34 UTC, RamyAlshurafa commented on client/src/App.js
> +              Component={() => <TestLanding onLogin={() => {}} />}
```suggestion
              Component={TestLanding}
```

2021-01-25 14:41 UTC, thejoefriel commented on client/src/pages/TestLanding/index.js
> +const Landing = () => {
done

2021-01-25 14:41 UTC, thejoefriel commented on client/src/pages/TestLanding/index.js
> +      {/* <BackLink mb="5" /> */}
deleted

2021-01-25 14:41 UTC, thejoefriel commented on client/src/pages/TestLanding/style.js
> +  ${setMargin}
done

2021-01-25 14:43 UTC, thejoefriel commented on client/src/App.js
> +              Component={() => <TestLanding onLogin={() => {}} />}
fixed

2021-01-26 09:54 UTC, RamyAlshurafa approved these changes

2021-01-26 09:55 UTC, merged