37 create menu component
yalla-coop/scouts pull request #97
Opened 2021-01-24 11:35 UTC by fadeomar

#### Issues this PR relates to
#37 
---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-01-25 09:22 UTC, thejoefriel requested changes
- [ ] Remove the color change on hover effect - the blue on blue isn't accessible to read. Maybe try making bold if we want an effect?
- [ ] Search icon in top navbar should go to HELP route

2021-01-25 09:22 UTC, thejoefriel commented on client/src/components/Icon/icons/Search.js
> +      stroke="#1E1E1E"
Pass down the color as a prop on these

2021-01-25 09:22 UTC, thejoefriel commented on client/src/components/Icon/icons/Search.js
> +      stroke="#1E1E1E"
It would be editing the stroke parameter just like how fill is done on others

2021-01-25 09:22 UTC, thejoefriel commented on client/src/components/Layout/index.js
> +  const [selectedKey, setSelectedKey] = useState('0');
This isn't necessarily a requested change, but it seems odd that this state isn't in the actual nav components. It doesn't feel like a pure approach even though it works perfectly well. I wonder if instead the nav component should be detecting the route and based on that deciding the selected menu item. 

@RamyAlshurafa what are your thoughts on this?

2021-01-25 09:22 UTC, thejoefriel commented on client/src/components/Menu/index.js
> +    routes: NAV_ROUTES.volunteer.VOLUNTEER_LOGGED_OUT,
These are all quite hard to read. I'd suggest destructuring higher up

2021-01-25 09:22 UTC, thejoefriel commented on client/src/components/Menu/style.js
> +    margin-bottom: 24px !important;
replace with theme.spacings

2021-01-25 09:22 UTC, thejoefriel commented on client/src/constants/nav-routes.js
> +const HELP = '/help';
change this to SEARCh and /search

2021-01-25 09:22 UTC, thejoefriel commented on client/src/components/Icon/icons/Burger.js
> +      stroke="#1E1E1E"
feed through color as a prop here

2021-01-25 09:57 UTC, RamyAlshurafa commented on client/src/components/Layout/index.js
> +  const [selectedKey, setSelectedKey] = useState('0');
yeah @fadeomar you can remove it and just defaultSelectedKeys={[0]}

2021-01-25 10:28 UTC, fadeomar commented on client/src/components/Icon/icons/Search.js
> +      stroke="#1E1E1E"
done 👍

2021-01-25 10:43 UTC, fadeomar commented on client/src/components/Layout/index.js
> +  const [selectedKey, setSelectedKey] = useState('0');
I had to save the selected key because the menu component renders from two Component the sidebar and the navbar, so in case selected something on the sidebar and then somehow opened the navbar, we should save the selected key because without it will not show any active key and if I add it statically will show the first element as active not the correct one, I dont think its effect on any other component

2021-01-25 10:54 UTC, fadeomar commented on client/src/components/Menu/index.js
> +    routes: NAV_ROUTES.volunteer.VOLUNTEER_LOGGED_OUT,
done

2021-01-25 10:57 UTC, fadeomar commented on client/src/components/Menu/style.js
> +    margin-bottom: 24px !important;
done

2021-01-25 10:58 UTC, fadeomar commented on client/src/constants/nav-routes.js
> +const HELP = '/help';
do you mean help ?

2021-01-25 10:58 UTC, fadeomar commented on client/src/components/Icon/icons/Burger.js
> +      stroke="#1E1E1E"
done

2021-01-26 09:47 UTC, thejoefriel commented on client/src/components/Layout/index.js
> +  const [selectedKey, setSelectedKey] = useState('0');
ok sure thing :)

2021-01-26 16:00 UTC, thejoefriel approved these changes

2021-01-26 16:00 UTC, merged